#! /bin/sh

# Start Window Compositor
picom --config ~/.config/picom/picom.conf --experimental-backends &

# Wacom graphic tablet
if [[ $(xsetwacom list devices) ]]; then
  xsetwacom set "$(xsetwacom list devices | head -n 1 | cut -f 1 | head -c -2)" MapToOutput HEAD-0
fi

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

if [[ $(xrandr -q | grep 'DP-1 connected')  ]]; then
	xrandr --output HDMI-0 --primary --mode 2560x1080 --rotate normal --output DP-1 --mode 1920x1080 --rotate normal --left-of HDMI-0
fi

bspc monitor DP-1 -d 5 6 7 8
bspc monitor HDMI-0 -d 1 2 3 4
bspc monitor DP-1 -s HDMI-0

bspc config border_width          2
bspc config border_radius        10
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#purple
bspc config focused_border_color "#bd93f9"
#blue
# bspc config focused_border_color "#6272a4"
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Problems With Java Applications
wmname LG3D

# Change Keyboard Layout
setxkbmap -option grp:alt_space_toggle br,us

# swap esc and casps
setxkbmap -option caps:swapescape

nitrogen --restore
#${HOME}/.config/polybar/launch.sh --forest &
polybar --config=~/.config/polybar/purple/config.ini &
